# Luego de subir el archivo IPS.rdf a virtuoso como grafo, 
# se presentan las siguientes ejemplos de consultas sparql.

sparql
PREFIX DS:<https://www.datos.gov.co/resource/thui-g47e/>
SELECT *
FROM <ips>
WHERE {
?y DS:ips_departamento ?x
} 
;


sparql
PREFIX DS:<https://www.datos.gov.co/resource/thui-g47e/>
SELECT ?nombre ?resultado ?unidades
FROM <ips>
WHERE {
?y DS:ips_ips ?nombre;
   DS:ips_resultado ?resultado;
   DS:ips_nomunidad ?unidades.
} 
;